name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: siteserver.azurecr.io
        username: siteserver
        password: ${{ secrets.REGISTRY_PASSWORD }}
          
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wotmudscriptssite
      working-directory: ./site

    - uses: actions/checkout@v2
    - name: Tag the Docker image
      run: docker tag wotmudscriptssite siteserver.azurecr.io/wotmudscriptssite
      working-directory: ./site

    - uses: actions/checkout@v2
    - name: Push the Docker image
      run: docker push siteserver.azurecr.io/wotmudscriptssite
      working-directory: ./site
