name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wotmudscriptssite

    - uses: actions/checkout@v2
    - name: Tag the Docker image
      run: docker tag wotmudscriptssite siteserver.azurecr.io/wotmudscriptssite
